//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Goudkoorts.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

// Deze class moet abstract worden
public abstract class Track : Block
{
    public Track()
    {
        ContainsMinecart = false;
    }

	public virtual bool ContainsMinecart
	{
		get;
		set;
	}

	public virtual Track NextTrack
	{
		get;
		set;

	}

	public virtual Track PreviousTrack
	{
		get;
		set;
	}

    public override char getChar()
    {
        return 't';
    }

	public override Block NextBlock
	{
		get
		{
			return NextTrack;
		}

		set
		{
			NextTrack = (Track)value;
		}

	}

	public virtual Boolean moveCart()
	{

		if (NextTrack.ContainsMinecart)
		{
			return false;
		}
		
		if(NextTrack is Switch)
		{

			Switch nextSwitch = (Switch)NextTrack;

			if(nextSwitch.PreviousTrack != this)
			{
				Console.WriteLine("switsh stands wrong");
				return false;
			}

		}

		NextTrack.ContainsMinecart = true;
		ContainsMinecart = false;

		return true;


	}

}

