//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Minecart
{
	public virtual Track Location
	{
		get;
		set;
	}

	public virtual bool Filled
	{
		get;
		set;
	}

	public virtual void Move()
	{
		throw new System.NotImplementedException();
	}

}

