//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Minecart
{
	public virtual Track Location
	{
		get;
		set;
	}

	public virtual bool Filled
	{
		get;
		set;
	}

	public Minecart(Track location)
	{

		Location = location;
		Location.ContainsMinecart = true;

	}

	public virtual Boolean Move()
	{
		Boolean b = Location.moveCart();
		Location = Location.NextTrack;
		return b;
	}

}

