//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Minecart
{
    public Minecart(Track location)
	{
		Location = location;
		Location.ContainsMinecart = true;
        Filled = true;
	}

	public virtual Track Location
	{
		get;
		set;
	}

	public virtual bool Filled
	{
		get;
		private set;
	}

	public virtual Boolean Move()
	{
        if (Location.NextTrack == null)
        {
            return true;
        }

        Location.ContainsMinecart = false;
        Location = Location.NextTrack;

        if (Location.ContainsMinecart == true)
        {
            return false;
        }
        
        Location.NextTrack.ContainsMinecart = true;
        return true;
	}

    public void empty()
    {
        Filled = false;
    }

}

