//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Goudkoorts.Model;

public class Ship
{
	public virtual int AmountGold
	{
		get;
		set;
	}

    public Water location
    {
        get;
        set;
    }

    public virtual bool full
    {
        get { return (!(AmountGold < 8)); }
    }

    public Ship(Water location)
    {
        this.location = location;
    }

	public virtual void Move()
	{
        location.hasShip = false;
        location.NextBlock.hasShip = true;
	}

    public void Fill()
    {
        AmountGold++;
    }

}

