//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameView
{
    public void showWelcome()
    {
        Console.WriteLine(" ███████   ███████  ██     ██ ████████  ██    ██   ███████   ███████  ████████  █████████  ███████");
        Console.WriteLine("██        ██     ██ ██     ██ ██     ██ ██   ██   ██     ██ ██     ██ ██     ██    ███    ████");
        Console.WriteLine("██    ███ ██     ██ ██     ██ ██     ██ ██████    ██     ██ ██     ██ ████████     ███     ███████");
        Console.WriteLine("██     ██ ██     ██ ██     ██ ██     ██ ██   ██   ██     ██ ██     ██ ██     ██    ███          ███");
        Console.WriteLine(" ███████   ███████   ███████  ████████  ██    ███  ███████   ███████  ██     ██    ███     ███████");
        Console.WriteLine("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=");
        Console.WriteLine("");
    }

    public void showBoard(String board)
    {
        Console.WriteLine(board);
    }

}

