//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameView
{
    public void printHeader()
    {
        Console.WriteLine("           ███████   ███████  ██     ██ ████████");
        Console.WriteLine("          ██        ██     ██ ██     ██ ██     ██");
        Console.WriteLine("          ██    ███ ██     ██ ██     ██ ██     ██");
        Console.WriteLine("          ██     ██ ██     ██ ██     ██ ██     ██");
        Console.WriteLine("           ███████   ███████   ███████  ████████");
        Console.WriteLine("");
        Console.WriteLine("██    ██   ███████   ███████  ████████  █████████  ███████");
        Console.WriteLine("██   ██   ██     ██ ██     ██ ██     ██    ███    ████");
        Console.WriteLine("██████    ██     ██ ██     ██ ████████     ███     ███████");
        Console.WriteLine("██   ██   ██     ██ ██     ██ ██     ██    ███          ███");
        Console.WriteLine("██    ███  ███████   ███████  ██     ██    ███     ███████");
        Console.WriteLine("-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
    }

    public void showWelcome()
    {
        printHeader();
        
        Console.WriteLine("███████████████████████ W E L K O M ███████████████████████");
        Console.WriteLine("█████                                                 █████");
        Console.WriteLine("█████ Welkom bij goudkoorts! Het doel van dit spel    █████");
        Console.WriteLine("█████ is om zo veel mogelijk mijnkarretjes met goud   █████");
        Console.WriteLine("█████ naar de boot te brengen. Jij moet de wissels    █████");
        Console.WriteLine("█████ omzetten zodat de karretjes niet botsen, maar   █████");
        Console.WriteLine("█████ kijk uit! De karretjes gaan steeds sneller!     █████");
        Console.WriteLine("█████                                                 █████");
        Console.WriteLine("█████ Gebruik de nummer toetsen om de wissels om te   █████");
        Console.WriteLine("█████ zetten.                                         █████");
        Console.WriteLine("█████                                                 █████");
        Console.WriteLine("██████████████████████ L E G E N D A ██████████████████████");
        Console.WriteLine("█████                                                 █████");
        Console.WriteLine("█████    0   - Vol karretje      o   - Leeg karretje  █████");
        Console.WriteLine("█████    -   - Rails             =   - Rangeervak     █████");
        Console.WriteLine("█████    /   - Wissel noord      \\   - Wissel zuid    █████");
        Console.WriteLine("█████    ~   - Water             +   - Kade           █████");
        Console.WriteLine("█████    }   - Volle boot        ]   - Lege boot      █████");
        Console.WriteLine("█████    X   - Silo                                   █████");
        Console.WriteLine("█████                                                 █████");
        Console.WriteLine("███████████████████████████████████████████████████████████");
        Console.WriteLine("");
        Console.WriteLine("> Druk op een toets om het spel te beginnen");
        
        Console.ReadKey();
    }

    public void showBoard(String board, int score)
    {
        Console.Clear();

        printHeader();

        Console.WriteLine("Score: {0}", score);
        Console.WriteLine();
        Console.WriteLine(board);
    }

	public Boolean GameOver()
	{
		Console.WriteLine("> Nog een keer spelen? (y/n)");

        var input = Console.ReadKey().KeyChar;
        Console.WriteLine("");

        while (input != 'y' && input != 'n')
        {
            Console.WriteLine("> ?");
            input = Console.ReadKey().KeyChar;
            Console.WriteLine("");
        }
        if (input == 'y')
        {
            return true;
        }
        return false;
	}

    public void showCrash()
    {
        Console.WriteLine("> Helaas, je bent gebotst!");
    }

    public void showExit()
    {
        Console.Clear();

        printHeader();

        Console.WriteLine("> Bedankt voor het spelen!");
        Console.WriteLine("> Druk op een toets om de applicatie af te sluiten");
        Console.ReadKey();
    }

    public char getInput()
    {
        var input = Console.ReadKey().KeyChar;
        Console.WriteLine("");
        return input;
    }

    public int getSwitchNumber()
    {
        char input = Console.ReadKey().KeyChar;
        int switchNumber = 0;

        int.TryParse(input.ToString(), out switchNumber);

        return switchNumber;
    }

}

