//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BoardController
{
	public virtual Track SpawnLocations
	{
		get;
		set;
	}

	public virtual IEnumerable<Track> Track
	{
		get;
		set;
	}

	public virtual IEnumerable<Minecart> Minecart
	{
		get;
		set;
	}

	public virtual IEnumerable<Ship> Ship
	{
		get;
		set;
	}

	public virtual BoardModel BoardModel
	{
		get;
		set;
	}

	public virtual string ShowBoard()
	{
		throw new System.NotImplementedException();
	}

}

