//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameController
{

    public BoardController boardController;
    public GameView gameView;

    public GameController()
    {
        boardController = new BoardController();
        gameView = new GameView();
    }

	public virtual int Turns
	{
		get;
		set;
	}

	public virtual int Score
	{
		get;
		set;
	}

	public virtual GameView GameView
	{
		get;
		set;
	}

	public virtual GameModel GameModel
	{
		get;
		set;
	}

	public virtual BoardController BoardController
	{
		get;
		set;
	}

	public virtual InputView InputView
	{
		get;
		set;
	}

    public void play()
    {
        gameView.showWelcome();
        boardController.generateBoard(10, 5);

        gameView.showBoard(boardController.ShowBoard());

		boardController.simulateTurn();

		gameView.showBoard(boardController.ShowBoard());
	}

	public void SimulateTurn()
	{
		throw new System.NotImplementedException();
	}


    


}

