//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameController
{
    public GameController()
    {
        GameView = new GameView();
        GameModel = new GameModel();
        BoardController = new BoardController();
        InputView = new InputView();
    }

	public virtual int Turns
	{
		get;
		set;
	}

	public virtual int Score
	{
		get;
		set;
	}

	public virtual GameView GameView
	{
		get;
		set;
	}

	public virtual GameModel GameModel
	{
		get;
		set;
	}

	public virtual BoardController BoardController
	{
		get;
		set;
	}

	public virtual InputView InputView
	{
		get;
		set;
	}

    public void play()
    {
        GameView.printHeader();
    }

	public virtual void SimulateTurn()
	{
		throw new System.NotImplementedException();
	}

}

