//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GameController
{

    public BoardController boardController;
    public GameView gameView;

	public virtual int Turns
	{
		get;
		set;
	}

	public virtual int Score
	{
		get;
		set;
	}

	public virtual GameView GameView
	{
		get;
		set;
	}

	public virtual GameModel GameModel
	{
		get;
		set;
	}

	public virtual BoardController BoardController
	{
		get;
		set;
	}

	public virtual InputView InputView
	{
		get;
		set;
	}

	public virtual void SimulateTurn()
	{
		throw new System.NotImplementedException();
	}


    public GameController()
    {

        boardController = new BoardController();
        gameView = new GameView();

        boardController.generateBoard(40, 40);

        gameView.showBoard(boardController.ShowBoard());

    }


}

